language: python

python: "2.7"

sudo: false

cache:
    directories:
        - $HOME/.cache/pip
        - _build

install: pip install git+https://github.com/valisj/sphinx git+https://github.com/valisj/sphinxcontrib-fulltoc

script: make html
