language: python

python: "2.7"

sudo: false

cache:
    directories:
        - $HOME/.cache/pip
        - _build

install: pip install sphinx~=1.3 git+https://github.com/fabpot/sphinx-php.git

script: make html
